## This configuration was generated by terraform-provider-oci

resource oci_database_db_system export_DB001003 {
  availability_domain = "HHnh:AP-MUMBAI-1-AD-1"
  #backup_network_nsg_ids = <<Optional value not found in discovery>>
  #backup_subnet_id = <<Optional value not found in discovery>>
  #cluster_name = <<Optional value not found in discovery>>
  compartment_id          = var.compartment_ocid
  cpu_core_count          = "2"
  data_storage_percentage = "80"
  data_storage_size_in_gb = "256"
  database_edition        = "ENTERPRISE_EDITION_HIGH_PERFORMANCE"
  db_home {
    #create_async = <<Optional value not found in discovery>>
    database {
      admin_password = "DBsggT-#T56t"
      #backup_id = <<Optional value not found in discovery>>
      #backup_tde_password = <<Optional value not found in discovery>>
      character_set = "AL32UTF8"
      #database_id = <<Optional value not found in discovery>>
      #database_software_image_id = <<Optional value not found in discovery>>
      db_backup_config {
        auto_backup_enabled = "false"
        auto_backup_window  = ""
        #recovery_window_in_days = <<Optional value not found in discovery>>
      }
      #db_domain = <<Optional value not found in discovery>>
      db_name     = "DB001003"
      db_workload = "OLTP"
      defined_tags = {
        "Oracle-Tags.CreatedBy" = "sureshanair@gmail.com"
        }
      freeform_tags = {
      }
      ncharacter_set = "AL16UTF16"
      #pdb_name = <<Optional value not found in discovery>>
      #tde_wallet_password = <<Optional value not found in discovery>>
      #time_stamp_for_point_in_time_recovery = <<Optional value not found in discovery>>
    }
    #database_software_image_id = <<Optional value not found in discovery>>
    db_version = "19.12.0.0"
    #defined_tags = <<Optional value not found in discovery>>
    display_name = "dbhome20211204174208"
    freeform_tags = {
    }
  }
  db_system_options {
    storage_management = "ASM"
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "sureshanair@gmail.com"
    #"Oracle-Tags.CreatedOn" = "2021-12-04T17:42:06.659Z"
  }
  disk_redundancy = "HIGH"
  display_name    = "DB001003"
  domain          = "sub11291638410.dbvcn.oraclevcn.com"
  fault_domains = [
    "FAULT-DOMAIN-1",
  ]
  freeform_tags = {
  }
  hostname = "db001003"
  #kms_key_id = <<Optional value not found in discovery>>
  #kms_key_version_id = <<Optional value not found in discovery>>
  license_model = "LICENSE_INCLUDED"
  #maintenance_window_details = <<Optional value not found in discovery>>
  node_count = "1"
  #nsg_ids = <<Optional value not found in discovery>>
  #private_ip = <<Optional value not found in discovery>>
  shape  = "VM.Standard2.2"
  source = "NONE"
  #source_db_system_id = <<Optional value not found in discovery>>
  #sparse_diskgroup = <<Optional value not found in discovery>>
  ssh_public_keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCGg97UW20Wz/H35Zvh+X7xndE7ZcSKUwxIBmbbzEnR4fozdqblodenNfcNKl+75fWnUzEHGgjc5VXpIdrcKX1yV48PUrVFogVkXITEAwJ3Sg0NlcmfNc+Ztei4rzDeDxEQ391VeYyi0GAdMo7x8W/VPLstZU5gjjFNjaN+w3UHZ5W2tMcNqUna/ryD+xbqaDev57oEYanvELyRbs4JiFEhAG6WIg0Z7gMvtZ7x44LSoZuDbqtUxDv81cy+7WuCFTj2GICu+Nte2gLMiu2IznxyvE8YK5O/eRiXqcLBp7LDH/65APzQvIPGJd2wVgiecIXIZJL2nALMaX0ah3lrNcxp rsa-key-20211129",
  ]
  subnet_id = "ocid1.subnet.oc1.ap-mumbai-1.aaaaaaaapgwi4dwwvomp3herr75gsx5rsqvjek53uhqygomqpagoc3ud6e2q"
  time_zone = "UTC"

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [db_home[0].database[0].admin_password]
  }
}

resource oci_database_pluggable_database export_pluggable_database_1 {
  container_database_id = "ocid1.database.oc1.ap-mumbai-1.anrg6ljr4twgpnaai2p3mrjt7sby4kow3d4aikrqsf4lbsb7jps65rcm5vta"
  defined_tags = {
  }
  freeform_tags = {
  }
  #pdb_admin_password = <<Optional value not found in discovery>>
  pdb_name = "DB001003_pdb1"
  #should_pdb_admin_account_be_locked = <<Optional value not found in discovery>>
  #tde_wallet_password = <<Optional value not found in discovery>>
}

